/*
 * Copyright 2011 Free Software Foundation, Inc.
 *
 * This file was generated by gr_modtool, a tool from the GNU Radio framework
 * This file is a part of gr-sc16io
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

#ifndef INCLUDED_SC16IO_API_H
#define INCLUDED_SC16IO_API_H

#include <gnuradio/attributes.h>

#ifdef gnuradio_sc16io_EXPORTS
#define SC16IO_API __GR_ATTR_EXPORT
#else
#define SC16IO_API __GR_ATTR_IMPORT
#endif

#endif /* INCLUDED_SC16IO_API_H */
