/*
 * Copyright 2026 Free Software Foundation, Inc.
 *
 * This file is part of GNU Radio
 *
 * SPDX-License-Identifier: GPL-3.0-or-later
 *
 */

/***********************************************************************************/
/* This file is automatically generated using bindtool and can be manually edited  */
/* The following lines can be configured to regenerate this file during cmake      */
/* If manual edits are made, the following tags should be modified accordingly.    */
/* BINDTOOL_GEN_AUTOMATIC(0)                                                       */
/* BINDTOOL_USE_PYGCCXML(0)                                                        */
/* BINDTOOL_HEADER_FILE(file_source_complex.h)                                        */
/* BINDTOOL_HEADER_FILE_HASH(ab94e97e00fdf8ff083adb4d9993393f)                     */
/***********************************************************************************/

#include <pybind11/complex.h>
#include <pybind11/pybind11.h>
#include <pybind11/stl.h>

namespace py = pybind11;

#include <gnuradio/sc16io/file_source_complex.h>
// pydoc.h is automatically generated in the build directory
#include <file_source_complex_pydoc.h>

void bind_file_source_complex(py::module& m)
{

    using file_source_complex    = gr::sc16io::file_source_complex;


    py::class_<file_source_complex, gr::sync_block, gr::block, gr::basic_block,
        std::shared_ptr<file_source_complex>>(m, "file_source_complex", D(file_source_complex))

        .def(py::init(&file_source_complex::make),
           D(file_source_complex,make)
        )
        



        ;




}








